apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Values.wzh-name }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Values.wzh-name }}"
    spec:
      containers:
      - name: "{{ .Values.wzh-name }}"
        image: "{{ .Values.imageRegistry }}"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1
            memory: 2Gi