apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
    spec:
      containers:
      - name: "{{ .Values.name }}"
        image: "{{ .Values.imageRegistry }}"
        ports:
        - containerPort: 8899
          name: admin
          protocol: TCP
        env:
        - name: LICENSE
          value: accept
        - name: ZOOKEEPER_SERVER
          value: dubbo-zookeeper
        - name: SERVER_PORT
          value: 8899
      