name: Tomcat 8
version: 1.0.0
description: Apache Tomcat is an open source implementation of the Java Servlet and JavaServer Pages technologies
icon: http://{{GIT_HOST}}/root/chart-demo/raw/master/stable/tomcat-8/icon/tomcat.png
status: OFFLINE
