apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: "{{ .Values.name }}"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
    spec:
      containers:
      - name: "{{ .Values.name }}"
        image: "{{ .Values.imageRegistry }}"
        ports:
        - containerPort: 2181
          name: admin
          protocol: TCP
        env:
        - name: LICENSE
          value: accept
        - name: ORACLE_PWD
          value: 2Szr6XUkBu25KCrs
      